### ISSUE TITLE
Datasets require updating - LF error inclusion

### ISSUE THREAD

**Issue by carenbarcelo-NOAA** [carenbarcelo-NOAA/Spatial-Assessment-Modeling-Workshop#12]
Hello - 

Many apologies, but we (the organizing team) have found an issue in the YFT OM that requires a fix. 

We will be updating ALL the YFT OM files to include LF error. 

Again, we apologize in advance as this fix will require analysts to re-clone the repo and use the updated datasets. 

Updated datasets will be available soon - please stay tuned.

Best,
Caren

**Comment by aaronmberger-nwfsc** [comment]
Caren, should this issue be closed as the bug and data sets have been fixed, correct?  Folks can still reference closed issues.
